- name: Ajouter la clé GPG officielle de Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Ajouter le dépôt Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Installer Docker
  apt:
    name: docker-ce
    state: present

- name: Activer et démarrer Docker
  service:
    name: docker
    state: started
    enabled: yes
