
services:
  front:
    image: nginx:alpine
    ports:
      - 127.0.0.1:${FRONT_PORT}:80  
    volumes:
      - ./front:/usr/share/nginx/html

  back:
    image: directus/directus
    ports:
      - 127.0.0.1:${BACK_PORT}:8055
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - db
    networks:
      - db-network  # Permet la communication avec la base

  db: 
    image: postgres:13
    ports: 
      - 127.0.0.1:${DB_PORT}:5432 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./back/init.sql:/docker-entrypoint-initdb.d/init.sql  # Script de création BDD
      - luxehaven-db-data:/var/lib/postgresql/data  # Volume persistant
    networks:
      - db-network

volumes:
  luxehaven-db-data: 

networks:
  db-network: # Réseau personnalisé pour isoler les services sensibles