
services:
  front:
    build:
      context: ./react-front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - back
    networks:
      - db-network

  back: 
    image: directus/directus
    ports:
      - "8055:8055"
    env_file:
      - .env
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: "pg"
      DB_HOST: "db"
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - db-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./back/init.sql:/docker-entrypoint-initdb.d/init.sql
      - luxehaven-db-data:/var/lib/postgresql/data
    networks:
      - db-network

volumes:
  luxehaven-db-data:

networks:
  db-network: