services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - luxehaven-db-preprod:/var/lib/postgresql/data
    networks:
      - app-network

  back:
    platform: linux/amd64
    image: ${DOCKER_USERNAME}/luxe-haven-back:latest
    ports:
      - "8055:8055"
    env_file:
      - preprod.env
    environment:
      DB_CLIENT: "pg"
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SECRET: ${SECRET}
    volumes:
      - /var/luxe-haven/uploads:/directus/uploads     # Sur disque VM GCP
      - /var/luxe-haven/extensions:/directus/extensions
    depends_on:
      - db
    networks:
      - app-network

  front:
    platform: linux/amd64
    image: ${DOCKER_USERNAME}/luxe-haven-front:latest
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  luxehaven-db-preprod:

networks:
  app-network:
