
services:
  front:
    image: nginx:alpine
    ports:
      - 80:80  
    volumes:
      - ./front:/usr/share/nginx/html

  back:
    image: directus/directus
    ports:
      - 8055:8055
    env_file:
      - .env
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: "pg"
      DB_HOST: "db"
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - db-network  # Permet la communication avec la base de données

  db: 
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./back/init.sql:/docker-entrypoint-initdb.d/init.sql  # Script de création BDD
      - luxehaven-db-data:/var/lib/postgresql/data  # Sauvegarde persistante des données
    networks:
      - db-network

volumes:
  luxehaven-db-data: 

networks:
  db-network: # # Réseau privé pour l’interconnexion des services backend et base de données