- name: Mise à jour des paquets
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Installer les paquets de base
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - git
    - unzip
