- name: Configuration et déploiement complet en production
  hosts: prod
  become: true

  vars_files:
    - ../group_vars/all.yml

  vars:
    image_tag: "prod"

  roles:
    - common
    - docker

  tasks:
    - name: Ajouter la clé publique de déploiement GitHub Actions
      authorized_key:
        user: issa
        state: present
        key: "{{ deployment_pubkey }}"

    - name: Pull et démarrage (ou mise à jour) du container luxe-haven-back
      community.docker.docker_container:
        name: luxe-haven-back
        image: "ghcr.io/issajaguraga/luxe-haven-back:{{ image_tag }}"
        state: started
        restart_policy: unless-stopped
        ports:
          - "8055:8055"

    - name: Pull et démarrage (ou mise à jour) du container luxe-haven-front
      community.docker.docker_container:
        name: luxe-haven-front
        image: "ghcr.io/issajaguraga/luxe-haven-front:{{ image_tag }}"
        state: started
        restart_policy: unless-stopped
        ports:
          - "8080:80"

    - name: Copier la config nginx
      template:
        src: ../templates/nginx-luxe-haven.conf.j2
        dest: /etc/nginx/sites-available/luxe-haven.conf
        owner: root
        group: root
        mode: '0644'

    - name: Activer le site nginx luxe-haven
      file:
        src: /etc/nginx/sites-available/luxe-haven.conf
        dest: /etc/nginx/sites-enabled/luxe-haven.conf
        state: link
        force: yes

    - name: Tester la configuration nginx
      command: nginx -t
      register: nginx_test
      ignore_errors: yes

    - name: Afficher le résultat du test nginx
      debug:
        var: nginx_test.stdout

    - name: Redémarrer nginx si la configuration est OK
      service:
        name: nginx
        state: restarted
      when: nginx_test.rc == 0
