- name: Configuration complète de la VM de préproduction
  hosts: preprod
  become: true

  vars_files:
    - ../group_vars/all.yml

  roles:
    - common
    - docker

- name: Ajoute la clé publique sur la VM
  hosts: preprod
  become: true
  tasks:
    - name: Ajouter la clé publique de déploiement GitHub Actions
      authorized_key:
        user: issa
        state: present
        key: "{{ lookup('file', 'id_rsa_gcloud.pub') }}"
