name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/issajaguraga/luxe-haven-back:${IMAGE_TAG} ./back
          docker push ghcr.io/issajaguraga/luxe-haven-back:${IMAGE_TAG}

      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/issajaguraga/luxe-haven-front:${IMAGE_TAG} ./react-front
          docker push ghcr.io/issajaguraga/luxe-haven-front:${IMAGE_TAG}

      - name: Set up Python and Ansible
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible and community.docker collection
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          ansible-galaxy collection install community.docker

      - name: Configure SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.78.3.240 >> ~/.ssh/known_hosts
          chmod 700 ~/.ssh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Ansible Playbook to deploy containers
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          ansible-playbook ansible/playbooks/deploy.yml -i ansible/inventory/prod_hosts.ini -e "image_tag=${IMAGE_TAG}"

      - name: Success message
        run: echo "Déploiement en production terminé avec succès !"
