name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python and Ansible
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Configure SSH access
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 34.78.3.240 >> ~/.ssh/known_hosts
        chmod 700 ~/.ssh
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Ansible Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
      run: |
        ansible-playbook ansible/playbooks/deploy.yml -i ansible/inventory/prod_hosts.ini

    - name: Success message
      run: echo "Déploiement en production terminé avec succès !"
