name: Preprod Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: luxehaven-project
      ZONE: europe-west1-b
      VM_NAME: preprod-vm
      REMOTE_USER: issa
      REMOTE_PATH: /home/issa/Luxe-Haven
      VM_IP: 35.246.87.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/luxe-haven-back:latest ./back

      - name: Push backend Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/luxe-haven-back:latest

      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/luxe-haven-front:latest ./react-front

      - name: Push frontend Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/luxe-haven-front:latest

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      # Setup SSH private key
      - name: Setup SSH private key
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_gcloud
          chmod 600 ~/.ssh/id_rsa_gcloud

      # Add remote VM IP to known_hosts to avoid SSH prompt
      - name: Add Google Cloud instance to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 35.246.87.12 >> ~/.ssh/known_hosts

      # Archive ansible folder
      - name: Archive ansible folder
        run: tar czf ansible.tar.gz ansible/

      # Copy ansible archive to remote VM via IAP tunnel using SSH key
      - name: Copy ansible archive to remote VM
        run: |
          gcloud compute scp --project=${{ env.PROJECT_ID }} --zone=${{ env.ZONE }} --tunnel-through-iap \
            --ssh-key-file $HOME/.ssh/id_rsa_gcloud \
            ansible.tar.gz ${{ env.REMOTE_USER }}@${{ env.VM_NAME }}:${{ env.REMOTE_PATH }}

      # Extract ansible archive on VM
      - name: Extract ansible archive on VM
        run: |
          gcloud compute ssh --project=${{ env.PROJECT_ID }} --zone=${{ env.ZONE }} --tunnel-through-iap \
            --ssh-key-file $HOME/.ssh/id_rsa_gcloud --ssh-flag="-tt" \
            ${{ env.REMOTE_USER }}@${{ env.VM_NAME }} -- "tar xzf ${{ env.REMOTE_PATH }}/ansible.tar.gz -C ${{ env.REMOTE_PATH }}"

      # Run Ansible playbook remotely
      - name: Run Ansible playbook remotely
        run: |
          gcloud compute ssh --project=${{ env.PROJECT_ID }} --zone=${{ env.ZONE }} --tunnel-through-iap \
            --ssh-key-file $HOME/.ssh/id_rsa_gcloud \
            ${{ env.REMOTE_USER }}@${{ env.VM_NAME }} -- \
            "cd ${{ env.REMOTE_PATH }}/ansible && ansible-playbook playbooks/site.yml -i inventory/hosts.ini --limit preprod"
