name: Preprod Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: luxehaven-project
      ZONE: europe-west1-b
      VM_NAME: preprod-vm
      REMOTE_USER: issa
      REMOTE_PATH: /home/issa/Luxe-Haven

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Connexion Docker Hub pour push/pull images
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build et push image backend Docker
      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/luxe-haven-back:latest ./back

      - name: Push backend Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/luxe-haven-back:latest

      # 4. Build et push image frontend Docker
      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/luxe-haven-front:latest ./react-front

      - name: Push frontend Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/luxe-haven-front:latest

      # 5. Authentification GCP avec la clé JSON
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 6. Installer Google Cloud SDK (sans options non supportées)
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      # 7. Archiver le dossier ansible
      - name: Archive ansible folder
        run: tar czf ansible.tar.gz ansible/

      # 8. Copier l’archive sur la VM via tunnel IAP
      - name: Copy ansible archive to remote VM via IAP tunnel
        run: |
          gcloud compute scp --project=${{ env.PROJECT_ID }} --zone=${{ env.ZONE }} --tunnel-through-iap \
            ansible.tar.gz ${{ env.REMOTE_USER }}@${{ env.VM_NAME }}:${{ env.REMOTE_PATH }}

      # 9. Décompresser l’archive sur la VM
      - name: Extract ansible archive on VM
        run: |
          gcloud compute ssh --project=${{ env.PROJECT_ID }} --zone=${{ env.ZONE }} --tunnel-through-iap \
            ${{ env.REMOTE_USER }}@${{ env.VM_NAME }} -- "tar xzf ${REMOTE_PATH}/ansible.tar.gz -C ${REMOTE_PATH}"

      # 10. Lancer le playbook ansible sur la VM via tunnel IAP SSH
      - name: Run Ansible playbook remotely via IAP tunnel
        run: |
          gcloud compute ssh --project=${{ env.PROJECT_ID }} --zone=${{ env.ZONE }} --tunnel-through-iap \
            ${{ env.REMOTE_USER }}@${{ env.VM_NAME }} -- \
            "cd ${REMOTE_PATH}/ansible && ansible-playbook playbooks/site.yml -i inventory/hosts.ini --limit preprod"
