name: Preprod Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/luxe-haven-back:latest ./back

      - name: Push backend Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/luxe-haven-back:latest

      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/luxe-haven-front:latest ./react-front

      - name: Push frontend Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/luxe-haven-front:latest

      - name: Copy ansible files to remote
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.PREPROD_HOST }}
          username: ${{ secrets.PREPROD_USER }}
          key: ${{ secrets.PREPROD_SSH_KEY }}
          source: "ansible/"
          target: "/home/issa/Luxe-Haven/ansible/"

      - name: Deploy with Ansible
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.PREPROD_HOST }}
          username: ${{ secrets.PREPROD_USER }}
          key: ${{ secrets.PREPROD_SSH_KEY }}
          script: |
            cd /home/issa/Luxe-Haven/ansible
            ansible-playbook playbooks/site.yml -i inventory/hosts.ini --limit preprod