name: Frontend CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --prefix react-front

      - name: Run tests with coverage
        run: npm run test:ci --prefix react-front

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: react-front
          args: >
            -Dsonar.projectKey=IssaJaguraga_Luxe-Haven
            -Dsonar.organization=luxe-haven
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build project
        run: npm run build --prefix react-front
